export default {
  vueI18n: {
    legacy: false,
    locale: "en",
    messages: {
      en: {
        welcome: "Welcome to to Wes-Con Warehouse",
        name: "Name",
        email: "Email",
        login: "login",
        password: "Password",
        signSucc: "You have succesfully signed in!",
        signError: "Please enter valid email and password",
        passError:
          "Passwords must be at least 6 characters or your passwords dont match",
        logOut: "Logout",
        home: "Home",
        aboutUs: "About Us",
        faq: "FAQ",
        contact: "Contact",
        services: "Services",
        dashboard: "Dashboard",
        selectDate: "Select Date",
        currentStock: "Current Stock",
        incoming: "Incoming",
        outgoing: "Outgoing",
        advices: "Advices",
        basedata: "Base Data ▿",
        search: "Search",
        message: "Message",
        settings: "Settings",
        creatDate: "Created Date",
        customer: "Customer",
        product: "Product",
        curQuantity: "Current Quantity",
        warehouse: "Warehouse",
        storDays: "Storage Days",
        stocks: "stocks",
        page1: "Page 1 of 1",
        expDate: "Expiry Date",
        quantity: "Quantity",
        cancel: "Cancel",
        save: "Save",
        incDate: "Incoming Date",
        prName: "Product Name",
        cusName: "CusName",
        desc: "Description",
        transType: "Transaction Type",
        clearAll: "Clear All",
        outDate: "Outgoing Date",
        shipNum: "Shipment",
        advType: "AdvType",
        advDate: "Advice Date",
        newAdv: "new advice",
        createNewAdv: "create new advice",
        refNummer: "Reference",
        referNummer: "Refer. number",
        type: "Type",
        select: "Select",
        charge: "Charge",
        isBooked: "Is Booked",
        commission: "Commission",
        category: "Category",
        container: "Container",
        width: "Width",
        length: "Length",
        height: "Height",
        weight: "Weight",
        addPr: "add product",
        pos: "position",
        prs: "Products",
        newPr: "new product",
        newCs: "new customer",
        cuss: "Customers",
        spaceName: "Space name",
        spaceCap: "Space Capacity",
        clear: "Clear",
        warehouses: "Warehouses",
        selectCus: "Select a customer",
        selectWare: "Select a warehouse",
        selectPr: "Select product",
        selectType: "Select type",
        notFound: "Nothing found...",
        filtCal: "Filter by Calendar",
        filtCus: "Filter by Customer",
        addNewInc: "Add New Incoming",
        quanError: "The quantity should be more than 1",
        makeOut: "Make New Outgoing",
        otherInfo: "Other Information",
        back: "Back",
        createPr: "Create product",
        lngName: "Long Name",
        det: "Details",
        asignCat: "Asign category",
        supCode: "Supplier Code",
        barcode: "Barcode",
        adviceID: "AdvID",
        cost: "Cost",
        accounts: "Accounts Table",
        costBearer: "Cost Bearer",
        adviceData: "Advice data",
        moreData: "more data for each advice",
        recCamp: "Reception camp",
        storDate: "Storage Date",
        commiss: "Commission",
        customerID: "Customer ID",
        custID: "Cust. ID",
        supplier: "Supplier",
        suppName: "Supplier Name",
        supOrder: "SupOrdNum",
        recipient: "Recipient",
        recipName: "Recipient Name",
        recipStr: "RecipStr",
        recipPLZ: "RecioPost",
        recipLKZ: "RecipCountrCode",
        carType: "Carrier Type",
        desc1: "Desc. 1",
        desc2: "Desc. 2",
        desc3: "Desc. 3",
        franking: "Franking",
        archive: "Archive",
        transMode: "Trans.mode",
        priority: "Priority",
        inst1: "Instruct. 1",
        inst2: "Instruct. 2",
        inst3: "Instruct. 3",
        instruction1: "Instruction 1",
        instruction2: "Instruction 2",
        instruction3: "Instruction 3",
        origSender: "Origin.sender",
        occurrence: "Occurrence",
        occurNum: "Occur.Num",
        creatDate2: "Created Date",
        transportMd: "Transport Mode",
        originalSd: "Original Sender",
        occurenceNm: "Occur.Number",
        occurenceTM: "Occur.Trans. Mode",
        OccurenceDt: "Occurence Date",
        manufacturer: "Manufacturer",
        supItems: "Supplier items",
        zollLand: "Cus-Num Or-Countr",
        zollTarif: "Cus-Tarif Num.",
        unit: "Unit",
        msgs: "Messages",
        FAQ: "FAQ",
        lupa: "🔍 ",
        sent: "📩",
        ask: "❓",
        suppliers: "Suppliers",
        delFrom: "Delivery from",
        delTo: "Delivery to",
        supDateFrom: "Sup.Date From",
        supDateTo: "Sup.Date To",
      },
      de: {
        welcome: "Willkommen im Wes-Con Warehouse",
        name: "Vorname",
        email: "Email",
        login: "ANMELDUNG",
        password: "Passwort",
        createAccount: "BENUTZERKONTO ERSTELLEN",
        signSucc: "Sie haben sich erfolgreich angemeldet",
        signError:
          "Bitte geben Sie eine gültige E-Mail-Adresse und ein Passwort ein",
        passError:
          "Passwörter müssen mindestens 6 Zeichen lang sein oder Ihre Passwörter stimmen nicht überein",
        logOut: "Ausloggen",
        home: "Startseite",
        aboutUs: "Über Uns",
        faq: "FAQ",
        contact: "Kontakt",
        services: "Dienstleistungen",
        dashboard: "Dashboard",
        selectDate: "Datum auswählen",
        currentStock: "Aktueller Lagerbestand",
        incoming: "Ankommend",
        outgoing: "Ausgehend",
        advices: "Beratung",
        basedata: "Basisdaten ▿",
        search: "Suchen",
        message: "Nachricht",
        settings: "Einstellungen",
        creatDate: "Erstellungsdatum",
        customer: "Kunde",
        product: "Produkt",
        curQuantity: "Aktuelle Menge",
        warehouse: "Warehouse",
        storDays: "Lagertage",
        stocks: "Aktien",
        page1: "Seite 1 von 1",
        expDate: "Verfallsdatum",
        quantity: "Menge",
        cancel: "Stornieren",
        save: "Speichern",
        incDate: "Eingehendes Datum",
        prName: "Produktname",
        cusName: "KdName",
        desc: "Beschreibung",
        transType: "Art der Transaktion",
        clearAll: "Alles löschen",
        outDate: "Ausgehendes Datum",
        shipNum: "Lieferungs",
        advType: "Berat.typ",
        advDate: "BewDat",
        newAdv: "neuer Beratung",
        createNewAdv: "Erstellen Sie neue Beratung",
        refNummer: "Referenz",
        type: "Typ",
        select: "wählen",
        charge: "Aufladung",
        isBooked: "ist gebucht",
        commission: "Kommission",
        category: "Kategorie",
        container: "Container",
        width: "Breite",
        length: "Länge",
        height: "Höhe",
        weight: "Gewicht",
        addPr: "Produkt hinzufügen",
        pos: "Position",
        prs: "Produkte",
        newPr: "Neues Produkt",
        newCs: "Neukunde",
        cuss: "Kunden",
        spaceName: "Raumname",
        spaceCap: "Platzkapazität",
        clear: "Löschen",
        warehouses: "Lagerhäuser",
        selectCus: "Wählen Sie einen Kunden aus",
        selectWare: "Wählen Sie ein Lager aus",
        notFound: "Nichts gefunden...",
        filtCal: "Nach Kalender filtern",
        filtCus: "Nach Kunde filtern",
        selectPr: "Ausgewähltes Produkt",
        addNewInc: "Neuen Eingang hinzufügen",
        quanError: "Die Menge sollte mehr als 1 betragen",
        makeOut: "Neuen Ausgang erstellen",
        selectType: "Typ auswählen",
        otherInfo: "Sonstige Informationen",
        lngName: "Lange Name",
        det: "Einzelheiten",
        asignCat: "Kategorie zuweisen",
        supCode: "Lieferantencode",
        barcode: "Barcode",
        back: "Zurück",
        createPr: "Produkt erstellen",
        adviceID: "AvisNr",
        cost: "Kostenstelle",
        accounts: "Kontentabelle",
        costBearer: "Kostenträger",
        adviceData: "Beratungsdaten",
        moreData: "mehr Daten für jeden Ratschlag",
        recCamp: "Aufnahmelager",
        storDate: "Speicherdat.",
        commiss: "Kommiss",
        custID: "Kunde ID",
        supplier: "Lieferant",
        suppName: "LieferantName",
        supOrder: "LiefBesNum",
        recipient: "Emp",
        recipName: "EmpName",
        recipStr: "EmpStr",
        recipPLZ: "EmpPLZ",
        recipLKZ: "EmpKLZ",
        carType: "Trägertyp",
        desc1: "Beschr. 1",
        desc2: "Beschr. 2",
        desc3: "Beschr. 3",
        franking: "Frankierung",
        archive: "Archiv",
        transMode: "Trans.mod.",
        priority: "Priorität",
        inst1: "Anweis. 1",
        inst2: "Anweis. 2",
        inst3: "Anweis. 3",
        instruction1: "Anweisung 1",
        instruction2: "Anweisung 2",
        instruction3: "Anweisung 3",
        origSender: "Ursp.Absender",
        occurrence: "Auftreten",
        occurNum: "Auftreten Num",
        creatDate2: "Ers.dat.",
        customerID: "Kundennummer",
        referNummer: "Referenznummer",
        transportMd: "Transportmodus",
        occurenceNm: "Vorkommensnummer",
        occurenceTM: "Vorkommen Transportmodus",
        OccurenceDt: "Auftretensdatum",
        manufacturer: "Hersteller",
        supItems: "Lieferantenartikel",
        zollLand: "Zoll-Nr Ur-Land",
        zollTarif: "Zoll-Tarif Nr.",
        unit: "Einheit",
        FAQ: "FAQ",
        lupa: "🔍 ",
        sent: "📩",
        ask: "❓",
        msgs: "Mitteilungen",
        suppliers: "Lieferanten",
        delFrom: "LiefVon",
        delTo: "LiefNach",
        supDateFrom: "LiefDatVon",
        supDateTo: "LiefDatBis",
      },
      du: {
        welcome: "Welkom bij Dashboard",
        name: "Naam",
        email: "E-mailen",
        login: "LOG IN",
        password: "Wachtwoord",
        signSucc: "Je bent succesvol ingelogd!",
        signError:
          "Wachtwoorden moeten minimaal 6 tekens lang zijn, anders komen uw wachtwoorden niet overeen",
        passError:
          "Wachtwoorden moeten minimaal 6 tekens lang zijn, anders komen uw wachtwoorden niet overeen",
        logOut: "Uitloggen",
        home: "Startpagina",
        aboutUs: "Over Ons",
        faq: "FAQ",
        contact: "Contact",
        services: "Diensten",
        dashboard: "Dashboard",
        selectDate: "Selecteer een datum",
        currentStock: "Huidige voorraad",
        incoming: "Inkomend",
        outgoing: "Uitgaand",
        advices: "Adviezen",
        basedata: "Basisgegevens ▿",
        search: "Zoekopdracht",
        message: "Bericht",
        settings: "Instellingen",
        creatDate: "Aanmaakdatum",
        customer: "Klant",
        product: "Product",
        curQuantity: "Huidige hoeveelheid",
        warehouse: "Magazijn",
        storDays: "Bewaardagen",
        stocks: "aandelen",
        page1: "Pagina 1 van 1",
        expDate: "Vervaldatum",
        quantity: "Hoeveelheid",
        cancel: "Annuleren",
        save: "Redden",
        incDate: "Inkomende datum",
        prName: "Productnaam",
        cusName: "Klantnaam",
        desc: "Beschrijving",
        transType: "Transactie Type",
        clearAll: "Wis alles",
        outDate: "Uitgaande datum",
        shipNum: "Verzend.",
        advType: "Adv.type",
        advDate: "AdvDatum",
        newAdv: "nieuw advies",
        createNewAdv: "nieuw advies creëren",
        refNummer: "Referentie",
        referNummer: "Referentienum.",
        type: "Type",
        select: "Selecteer",
        charge: "Aanval",
        isBooked: "Is geboekt",
        commission: "Commissie",
        category: "Categorie",
        container: "Houder",
        width: "Breedte",
        length: "Lengte",
        height: "Hoogte",
        weight: "Gewicht",
        addPr: "product toevoegen",
        pos: "positie",
        prs: "Producten",
        newPr: "nieuw product",
        newCs: "nieuwe klant",
        cuss: "Klanten",
        spaceName: "Naam van de ruimte",
        spaceCap: "Ruimtecapaciteit",
        clear: "Duidelijk",
        warehouses: "Magazijnen",
        selectCus: "Selecteer een klant",
        selectWare: "Selecteer een magazijn",
        selectPr: "Selecteer product",
        selectType: "Selecteer type",
        notFound: "Niets gevonden...",
        filtCal: "Filter op klant",
        filtCus: "Nach Kunde filtern",
        addNewInc: "Voeg nieuwe inkomende toe",
        quanError: "Het aantal moet groter zijn dan 1",
        makeOut: "Maak nieuw uitgaand",
        otherInfo: "Andere informatie",
        back: "Rug",
        createPr: "Product maken",
        lngName: "Lange naam",
        det: "Details",
        asignCat: "Categorie toewijzen",
        supCode: "Leverancierscode",
        barcode: "Streepjescode",
        adviceID: "AdvID",
        cost: "Kosten",
        accounts: "Rekeningentabel",
        costBearer: "Kostendrager",
        adviceData: "Advies gegevens",
        moreData: "meer gegevens voor elk advies",
        recCamp: "Ontvangst kamp",
        storDate: "Opslagdatum",
        commiss: "Commissie",
        customerID: "Klanten ID",
        custID: "Klant. ID",
        supplier: "Leverancier",
        suppName: "NaamLever.",
        supOrder: "Lief.BestNum.",
        recipient: "Ontvanger",
        recipName: "NaamOntv.",
        recipStr: "StraatOntv.",
        recipPLZ: "ZIPOntv.",
        recipLKZ: "LandCodeOntv.",
        carType: "TypeVervoer",
        desc1: "Besch.1",
        desc2: "Besch.2",
        desc3: "Besch.3",
        franking: "Frankeren",
        archive: "Archief",
        transMode: "Vervoerd. mode",
        priority: "Prioriteit",
        inst1: "Instruct. 1",
        inst2: "Instruct. 2",
        inst3: "Instruct. 3",
        instruction1: "Instructie 1",
        instruction2: "Instructie 2",
        instruction3: "Instructie 3",
        origSender: "Origin.afzen.",
        occurrence: "Voorkomen",
        occurNum: "Voorvalnummer",
        creatDate2: "Aanmaakdat.",
        transportMd: "Transportmodus",
        originalSd: "Orig. afzender",
        occurenceNm: "Voorvalnummer",
        occurenceTM: "Voorval Trans.modus",
        OccurenceDt: "Datum van voork.",
        manufacturer: "Fabrikant",
        supItems: "Artikelen van leveranciers",
        zollLand: "Cus-Num Or-Countr",
        zollTarif: "Cus-Tarif Num.",
        unit: "Eenheid",
        msgs: "Berichten",
        FAQ: "FAQ",
        lupa: "🔍 ",
        sent: "📩",
        ask: "❓",
        suppliers: "Leveranciers",
        delFrom: "Levering vanaf",
        delTo: "Leveren aan",
        supDateFrom: "Lev.Datum Van",
        supDateTo: "Lev.Datum Tot",
      },
    },
  },
  locales: ["en", "de", "du"], // Define your supported locales
  defaultLocale: "en", // Set default locale
};
