export default {
  vueI18n: {
    legacy: false,
    locale: "en",
    messages: {
      en: {
        home: "Home",
        aboutUs: "About Us",
        contacts: "Contacts",
        services: "Services",
        mainPageH1: "enc cultural and heritage tours",
      },
      de: {
        home: "Startseite",
        aboutUs: "Über Uns",
        contact: "Kontakt",
        services: "Dienstleistungen",
        mainPageH1: "ENC Kultur- und Kulturerbetouren",
      },
      es: {
        home: "Startpagina",
        aboutUs: "Sobre nosotros",
        contact: "Contactos",
        services: "Servicios",
        mainPageH1: "ENC Tours culturales y patrimoniales",
      },
      it: {
        home: "Startpagina",
        aboutUs: "Sobre nosotros",
        contact: "Contactos",
        services: "Servicios",
        mainPageH1: "ENC Tours culturali e patrimoniali",
      },
      jp: {
        home: "Startpagina",
        aboutUs: "Sobre nosotros",
        contact: "Contactos",
        services: "Servicios",
        mainPageH1: "ENC ツアーの文化と伝統",
      },
      fr: {
        home: "Startpagina",
        aboutUs: "Sobre nosotros",
        contact: "Contactos",
        services: "Servicios",
        mainPageH1: "ENC Tours culturais e patrimoniais",
      },
      pt: {
        home: "Startpagina",
        aboutUs: "Sobre nosotros",
        contact: "Contactos",
        services: "Servicios",
        mainPageH1: "ENC Tours culturais e patrimoniais",
      },
      kr: {
        home: "Startpagina",
        aboutUs: "Sobre nosotros",
        contact: "Contactos",
        services: "Servicios",
        mainPageH1: "ENC 투어 문화와 유산",
      },
    },
  },
  locales: ["en", "de", "es", "it", "jp", "fr", "pt", "kr"],
  defaultLocale: "en",
};