export const localeCodes = ["en","de","es","it","jp","fr","pt","kr"]

export const localeMessages = {
}

export const additionalMessages = Object({"de":[],"es":[],"it":[],"jp":[],"fr":[],"pt":[],"kr":[],})

export const resolveNuxtI18nOptions = async (context) => {
  const nuxtI18nOptions = Object({})
  const vueI18nOptionsLoader = async (context) => Object({"legacy":false,"locale":"en","messages": Object({"en":{
  "home": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Home"])};fn.source="Home";return fn;})(),
  "aboutUs": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["About Us"])};fn.source="About Us";return fn;})(),
  "contacts": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Contacts"])};fn.source="Contacts";return fn;})(),
  "services": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Services"])};fn.source="Services";return fn;})(),
  "mainPageH1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["enc cultural and heritage tours"])};fn.source="enc cultural and heritage tours";return fn;})(),
  "comp2p1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Inspirations"])};fn.source="Inspirations";return fn;})(),
  "comp2p2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["The excitement never ends with us!"])};fn.source="The excitement never ends with us!";return fn;})(),
  "comp2p3": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Inspired by the abundance of travel options in our Asia, we have travelled to every nook and corner of our beloved destinations to find what we define as exemplary tours for discerning travel connoisseurs"])};fn.source="Inspired by the abundance of travel options in our Asia, we have travelled to every nook and corner of our beloved destinations to find what we define as exemplary tours for discerning travel connoisseurs";return fn;})(),
  "specialP1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["OIL BOOM AND ARCHITECTURE TOUR"])};fn.source="OIL BOOM AND ARCHITECTURE TOUR";return fn;})(),
  "specialP2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["FLOWER WATCHING TOURS"])};fn.source="FLOWER WATCHING TOURS";return fn;})(),
  "specialP3": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["RELIGIOUS TOURS"])};fn.source="RELIGIOUS TOURS";return fn;})(),
  "specialP4": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["GOURMET TOUR"])};fn.source="GOURMET TOUR";return fn;})(),
  "specialP5": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["BIRD WATCHING TOUR"])};fn.source="BIRD WATCHING TOUR";return fn;})(),
  "specialP6": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["GOLF TOUR"])};fn.source="GOLF TOUR";return fn;})(),
  "specialP7": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["POMEGRANATE TOUR"])};fn.source="POMEGRANATE TOUR";return fn;})(),
  "specialP8": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["AGRICULTURAL TOUR"])};fn.source="AGRICULTURAL TOUR";return fn;})(),
  "specialP9": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["CARPET AND LOCAL HERITAGE TOURS"])};fn.source="CARPET AND LOCAL HERITAGE TOURS";return fn;})(),
  "specialH1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["SPECIAL INTEREST TOURS"])};fn.source="SPECIAL INTEREST TOURS";return fn;})(),
  "specailH2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["LAUDED FOR ITS EXTENSIVE KNOWLEDGE, ITS EAST-MEETS-WEST MODEL AND VENTURING RESPONSIBLY INTO EVERY CORNER OF ITS DESTINATIONS, IT IS OUR MISSION TO SHOW GUESTS THE BEATING HEART OF OUR ASIA"])};fn.source="LAUDED FOR ITS EXTENSIVE KNOWLEDGE, ITS EAST-MEETS-WEST MODEL AND VENTURING RESPONSIBLY INTO EVERY CORNER OF ITS DESTINATIONS, IT IS OUR MISSION TO SHOW GUESTS THE BEATING HEART OF OUR ASIA";return fn;})(),
  "genFacts": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["GENERAL FACTS"])};fn.source="GENERAL FACTS";return fn;})(),
  "genP1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Welcome to Azerbaijan! This is the Land of Fire and the Pearl of the Caucasus, a land where eastern colors combine magnificently with western progress. Azerbaijan is a country of unique nature, unmatched culture, centuries of history with its customs and traditions and fine cuisine; a place which will satisfy the expectations of the most sophisticated gastronomists, and finally, it is the country of Caucasian hospitality and friendliness."])};fn.source="Welcome to Azerbaijan! This is the Land of Fire and the Pearl of the Caucasus, a land where eastern colors combine magnificently with western progress. Azerbaijan is a country of unique nature, unmatched culture, centuries of history with its customs and traditions and fine cuisine; a place which will satisfy the expectations of the most sophisticated gastronomists, and finally, it is the country of Caucasian hospitality and friendliness.";return fn;})(),
  "genP2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Azerbaijan is situated at the eastern side of the Transcaucasia (or South Caucasus) on the shores of the Caspian Sea. The population of Azerbaijan exceeds 9.8 million and the territory covers an area of 86 600 square kilometers. According to both of these figures, Azerbaijan is the largest country of the South Caucasus. The City of Baku is the capital and the country’s largest city. The National language here is Azerbaijani. However, Russian is also widely used and many younger residents also speak English. Azerbaijan shares borders with Iran (765 km), Turkey (15 km), Russia (390 km), Georgia (480 km) and Armenia (1007 km). The eastern shores of the country are washed by the waters of the Caspian Sea."])};fn.source="Azerbaijan is situated at the eastern side of the Transcaucasia (or South Caucasus) on the shores of the Caspian Sea. The population of Azerbaijan exceeds 9.8 million and the territory covers an area of 86 600 square kilometers. According to both of these figures, Azerbaijan is the largest country of the South Caucasus. The City of Baku is the capital and the country’s largest city. The National language here is Azerbaijani. However, Russian is also widely used and many younger residents also speak English. Azerbaijan shares borders with Iran (765 km), Turkey (15 km), Russia (390 km), Georgia (480 km) and Armenia (1007 km). The eastern shores of the country are washed by the waters of the Caspian Sea.";return fn;})(),
  "genP3": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Historically a part of the Great Silk Road and situated at the crossroads of the geopolitical, economic and cultural interests of many nations and civilizations, Azerbaijan has, since ancient times, aroused the interests of great minds, scientists, travelers and historians. References to this amazing land, located on the western coast of the Caspian Sea and in the eastern part of the South Caucasus, can be found in the ancient writings of Herodotus, Strabo, and Claudius Ptolemy. Azerbaijan has an amazing historical and cultural heritage with more than 7500 natural, archeological, architectural, and historical monuments. Cave drawings at Gobustan, Momine-Khatun and Garabaghlar mausoleums, the Palace of Sheki Khans, the Maiden Tower, the castles of Absheron, medieval manuscripts decorated with magnificent miniature paintings, antique rugs, and works of literature, arts and sculpture – all of this is just a small part of the country’s rich and priceless heritage."])};fn.source="Historically a part of the Great Silk Road and situated at the crossroads of the geopolitical, economic and cultural interests of many nations and civilizations, Azerbaijan has, since ancient times, aroused the interests of great minds, scientists, travelers and historians. References to this amazing land, located on the western coast of the Caspian Sea and in the eastern part of the South Caucasus, can be found in the ancient writings of Herodotus, Strabo, and Claudius Ptolemy. Azerbaijan has an amazing historical and cultural heritage with more than 7500 natural, archeological, architectural, and historical monuments. Cave drawings at Gobustan, Momine-Khatun and Garabaghlar mausoleums, the Palace of Sheki Khans, the Maiden Tower, the castles of Absheron, medieval manuscripts decorated with magnificent miniature paintings, antique rugs, and works of literature, arts and sculpture – all of this is just a small part of the country’s rich and priceless heritage.";return fn;})(),
  "genP4": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Azerbaijan is often referred to as the “Land of Fire”. It is known that the majority of those residing on this territory before the Common Era were fire worshippers. Since then, the country has preserved the ancient evidence of that era: cave paintings, statues of gods and ancient temples. Two of the most vivid examples of this heritage are the temple of fire-worshippers (“Ateshgah”) at Surakhani near Baku and “Yanardagh”, translated as the “burning mountain”. According to legend, “Ateshgah” temple was built by Indian fire worshippers, who arrived here after learning about the eternally burning fire, emitted from the ground, and were so amazed by what they had seen, that they decided to build a temple on this very place. These lands were considered to be sacred for centuries and throughout history were worshipped by the followers of Zoroastrianism, Hinduism and Sikhism."])};fn.source="Azerbaijan is often referred to as the “Land of Fire”. It is known that the majority of those residing on this territory before the Common Era were fire worshippers. Since then, the country has preserved the ancient evidence of that era: cave paintings, statues of gods and ancient temples. Two of the most vivid examples of this heritage are the temple of fire-worshippers (“Ateshgah”) at Surakhani near Baku and “Yanardagh”, translated as the “burning mountain”. According to legend, “Ateshgah” temple was built by Indian fire worshippers, who arrived here after learning about the eternally burning fire, emitted from the ground, and were so amazed by what they had seen, that they decided to build a temple on this very place. These lands were considered to be sacred for centuries and throughout history were worshipped by the followers of Zoroastrianism, Hinduism and Sikhism.";return fn;})(),
  "genP5": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["The fire rhetoric, passed from generation to generation, has been reflected in the many artistic works of Azerbaijani masters throughout the centuries, and has recently reached its culmination in the form of The “Flame Towers” complex. Constructed in Baku not long ago, the Flame Towers have, in very a short period of time, become a breathtaking architectural landmark of the capital city, embodying a tribute to our history, and representing contemporary Azerbaijan – a new, ambitious country, developing and progressive, but still loyal to its roots and origins."])};fn.source="The fire rhetoric, passed from generation to generation, has been reflected in the many artistic works of Azerbaijani masters throughout the centuries, and has recently reached its culmination in the form of The “Flame Towers” complex. Constructed in Baku not long ago, the Flame Towers have, in very a short period of time, become a breathtaking architectural landmark of the capital city, embodying a tribute to our history, and representing contemporary Azerbaijan – a new, ambitious country, developing and progressive, but still loyal to its roots and origins.";return fn;})(),
  "genP6": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Azerbaijan is the West in the East and the East in the West! Welcome!"])};fn.source="Azerbaijan is the West in the East and the East in the West! Welcome!";return fn;})(),
  "area": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["AREA"])};fn.source="AREA";return fn;})(),
  "areaP": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Azerbaijan is situated in the Caucasus region of Eurasia. Three physical features dominate Azerbaijan: the Caspian Sea, whose shoreline forms a natural boundary to the east; the Greater Caucasus mountain range to the north; and the extensive flatlands at the country’s center. About the size of Portugal or the state of Maine, Azerbaijan has a total land area of approximately 86,600 square kilometers, less than 1% of the land area of the former Soviet Union."])};fn.source="Azerbaijan is situated in the Caucasus region of Eurasia. Three physical features dominate Azerbaijan: the Caspian Sea, whose shoreline forms a natural boundary to the east; the Greater Caucasus mountain range to the north; and the extensive flatlands at the country’s center. About the size of Portugal or the state of Maine, Azerbaijan has a total land area of approximately 86,600 square kilometers, less than 1% of the land area of the former Soviet Union.";return fn;})(),
  "population": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["POPULATION"])};fn.source="POPULATION";return fn;})(),
  "popP": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["The current population of Azerbaijan is 10,126,684 as of Monday, May 11, 2020, based on the latest United Nations estimates. Azerbaijan population is equivalent to 0.13% of the total world population."])};fn.source="The current population of Azerbaijan is 10,126,684 as of Monday, May 11, 2020, based on the latest United Nations estimates. Azerbaijan population is equivalent to 0.13% of the total world population.";return fn;})(),
  "capital": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["CAPITAL"])};fn.source="CAPITAL";return fn;})(),
  "capP": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Baku is the capital and largest city of Azerbaijan, as well as the largest city on the Caspian Sea and of the Caucasus region. Baku is located 28 meters below sea level, which also makes it the lowest lying national capital in the world."])};fn.source="Baku is the capital and largest city of Azerbaijan, as well as the largest city on the Caspian Sea and of the Caucasus region. Baku is located 28 meters below sea level, which also makes it the lowest lying national capital in the world.";return fn;})(),
  "lang": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["LANGUAGE"])};fn.source="LANGUAGE";return fn;})(),
  "langP": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Azerbaijani is the official language of Azerbaijan. It is also the language of the majority population of the country. Russian and English are widely spoken as well."])};fn.source="Azerbaijani is the official language of Azerbaijan. It is also the language of the majority population of the country. Russian and English are widely spoken as well.";return fn;})(),
  "religion": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["RELIGION"])};fn.source="RELIGION";return fn;})(),
  "religP": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Majority of population is Muslim. Other religions are also practiced such as Judaism, Orthodox and Catholic. The country is tolerant and apart from the mosques you can find churches and synagogues both in the capital city Baku and the countryside as well."])};fn.source="Majority of population is Muslim. Other religions are also practiced such as Judaism, Orthodox and Catholic. The country is tolerant and apart from the mosques you can find churches and synagogues both in the capital city Baku and the countryside as well.";return fn;})(),
  "currency": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["CURRENCY"])};fn.source="CURRENCY";return fn;})(),
  "currencyP": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["The Azerbaijan Manat is the currency of Azerbaijan. The current exchange rate is 1 USD is 1.70 AZN, 1 Euro is 1.84 AZN. Dollar and Euro can be easily exchanged at the local banks and airport."])};fn.source="The Azerbaijan Manat is the currency of Azerbaijan. The current exchange rate is 1 USD is 1.70 AZN, 1 Euro is 1.84 AZN. Dollar and Euro can be easily exchanged at the local banks and airport.";return fn;})(),
  "time": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["TIME"])};fn.source="TIME";return fn;})(),
  "timeP": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["AZT – Azerbaijan Time (Standard Time) currently has same time zone offset as AZT (UTC +4) but different time zone name. Azerbaijan Time (AZT) is 4 hours ahead of Coordinated Universal Time (UTC). This time zone is in use during standard time in: Asia."])};fn.source="AZT – Azerbaijan Time (Standard Time) currently has same time zone offset as AZT (UTC +4) but different time zone name. Azerbaijan Time (AZT) is 4 hours ahead of Coordinated Universal Time (UTC). This time zone is in use during standard time in: Asia.";return fn;})(),
  "climate": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["CLIMATE"])};fn.source="CLIMATE";return fn;})(),
  "climP": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["9 out of 11 climate zones are available in Azerbaijan, from Subtropics to Alpine climates can be witnessed."])};fn.source="9 out of 11 climate zones are available in Azerbaijan, from Subtropics to Alpine climates can be witnessed.";return fn;})(),
  "airports": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["AIRPORTS"])};fn.source="AIRPORTS";return fn;})(),
  "airP": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["International Airports: Baku, Ganja, Lankaran, Naxchivan, Gabala"])};fn.source="International Airports: Baku, Ganja, Lankaran, Naxchivan, Gabala";return fn;})(),
  "mainCities": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["MAIN CITIES"])};fn.source="MAIN CITIES";return fn;})(),
  "citiesP": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Baku, Ganja, Sumqayit, Shamakhi, Quba, Sheki, Qabala, Lankaran"])};fn.source="Baku, Ganja, Sumqayit, Shamakhi, Quba, Sheki, Qabala, Lankaran";return fn;})(),
  "points": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["HIGHEST POINTS"])};fn.source="HIGHEST POINTS";return fn;})(),
  "pointsP": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["The highest peaks in the Republic of Azerbaijan are situated in the Greater Caucasus, the Lesser Caucasus and Talysh mountain systems. The highest peak in the Republic of Azerbaijan is Bazarduzu (Bigger Caucasus) (4,466 metres (14,656 ft)"])};fn.source="The highest peaks in the Republic of Azerbaijan are situated in the Greater Caucasus, the Lesser Caucasus and Talysh mountain systems. The highest peak in the Republic of Azerbaijan is Bazarduzu (Bigger Caucasus) (4,466 metres (14,656 ft)";return fn;})(),
  "mainRivers": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["MAIN RIVERS"])};fn.source="MAIN RIVERS";return fn;})(),
  "riversP": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["The rivers of Azerbaijan can be divided into three groups: the rivers of the Kursk basin (Kaniks, Kabirri, Turyan, Agstafa, Shekir, Terter, Khachin, etc.). the Rivers of the Araks basin (Arpachay, Nakhchivan, Ohchu, Hekeri). , Kondelenchay, etc.), which flows directly into the Caspian sea (Samur, Gudyal, Velvele, Vilesh, Lankaran, etc.)"])};fn.source="The rivers of Azerbaijan can be divided into three groups: the rivers of the Kursk basin (Kaniks, Kabirri, Turyan, Agstafa, Shekir, Terter, Khachin, etc.). the Rivers of the Araks basin (Arpachay, Nakhchivan, Ohchu, Hekeri). , Kondelenchay, etc.), which flows directly into the Caspian sea (Samur, Gudyal, Velvele, Vilesh, Lankaran, etc.)";return fn;})(),
  "mainLakes": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["MAIN LAKES"])};fn.source="MAIN LAKES";return fn;})(),
  "lakesP": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["The list includes only natural lakes. Artificial lakes, such as reservoirs, are excluded from this list. The Caspian sea, which is the largest lake on Earth, both in area and volume, and which borders Azerbaijan to the East, is also excluded from this list. There are about 450 lakes in Azerbaijan."])};fn.source="The list includes only natural lakes. Artificial lakes, such as reservoirs, are excluded from this list. The Caspian sea, which is the largest lake on Earth, both in area and volume, and which borders Azerbaijan to the East, is also excluded from this list. There are about 450 lakes in Azerbaijan.";return fn;})(),
  "electricity": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["ELECTRICITY"])};fn.source="ELECTRICITY";return fn;})(),
  "elecP": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Non-grounded outlets are more common than grounded ones. It is recommend both styles of adapters be taken. Azerbaijan has 220 volt electricity, meaning unless your computer or appliance is dual voltage or designed for 220 volts, you will need a converter or transformer. The cycles (Hz) are 50 per second."])};fn.source="Non-grounded outlets are more common than grounded ones. It is recommend both styles of adapters be taken. Azerbaijan has 220 volt electricity, meaning unless your computer or appliance is dual voltage or designed for 220 volts, you will need a converter or transformer. The cycles (Hz) are 50 per second.";return fn;})(),
  "reqVisa": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["REQUIREMENTS OF VISA"])};fn.source="REQUIREMENTS OF VISA";return fn;})(),
  "reqVisaP": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Please, apply for e-Visa at www.evisa.gov.az"])};fn.source="Please, apply for e-Visa at www.evisa.gov.az";return fn;})()
},"de":{
  "home": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Startseite"])};fn.source="Startseite";return fn;})(),
  "aboutUs": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Über Uns"])};fn.source="Über Uns";return fn;})(),
  "contact": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Kontakt"])};fn.source="Kontakt";return fn;})(),
  "services": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Dienstleistungen"])};fn.source="Dienstleistungen";return fn;})(),
  "mainPageH1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["ENC Kultur- und Kulturerbetouren"])};fn.source="ENC Kultur- und Kulturerbetouren";return fn;})(),
  "comp2p1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Inspirationen"])};fn.source="Inspirationen";return fn;})(),
  "comp2p2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Bei uns hört die Aufregung nie auf!"])};fn.source="Bei uns hört die Aufregung nie auf!";return fn;})(),
  "comp2p3": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Inspiriert von der Fülle an Reisemöglichkeiten in unserem Asien sind wir in jeden Winkel unserer geliebten Reiseziele gereist, um das zu finden, was wir als beispielhafte Touren für anspruchsvolle Reisekenner bezeichnen"])};fn.source="Inspiriert von der Fülle an Reisemöglichkeiten in unserem Asien sind wir in jeden Winkel unserer geliebten Reiseziele gereist, um das zu finden, was wir als beispielhafte Touren für anspruchsvolle Reisekenner bezeichnen";return fn;})(),
  "specialP1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["ÖLBOOM UND ARCHITEKTUR-TOUR"])};fn.source="ÖLBOOM UND ARCHITEKTUR-TOUR";return fn;})(),
  "specialP2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["BLUMEN BEOBACHTEN TOUREN"])};fn.source="BLUMEN BEOBACHTEN TOUREN";return fn;})(),
  "specialP3": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["RELIGIÖSE TOUREN"])};fn.source="RELIGIÖSE TOUREN";return fn;})(),
  "specialP4": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["GOURMET TOUR"])};fn.source="GOURMET TOUR";return fn;})(),
  "specialP5": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["VOGELBEOBACHTUNGSTOUR"])};fn.source="VOGELBEOBACHTUNGSTOUR";return fn;})(),
  "specialP6": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["GOLFTOUR"])};fn.source="GOLFTOUR";return fn;})(),
  "specialP7": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["GRANATAPFEL TOUR"])};fn.source="GRANATAPFEL TOUR";return fn;})(),
  "specialP8": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["LANDWIRTSCHAFTLICHE TOUR"])};fn.source="LANDWIRTSCHAFTLICHE TOUR";return fn;})(),
  "specialP9": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["TEPPICH UND LOKALE ERBE TOUREN"])};fn.source="TEPPICH UND LOKALE ERBE TOUREN";return fn;})(),
  "specialH1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["BESONDERE INTERRESE TOUREN"])};fn.source="BESONDERE INTERRESE TOUREN";return fn;})(),
  "specailH2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["LAUDED FOR ITS EXTENSIVE KNOWLEDGE, ITS EAST-MEETS-WEST MODEL AND VENTURING RESPONSIBLY INTO EVERY CORNER OF ITS DESTINATIONS, IT IS OUR MISSION TO SHOW GUESTS THE BEATING HEART OF OUR ASIA"])};fn.source="LAUDED FOR ITS EXTENSIVE KNOWLEDGE, ITS EAST-MEETS-WEST MODEL AND VENTURING RESPONSIBLY INTO EVERY CORNER OF ITS DESTINATIONS, IT IS OUR MISSION TO SHOW GUESTS THE BEATING HEART OF OUR ASIA";return fn;})()
},"es":{
  "home": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Startpagina"])};fn.source="Startpagina";return fn;})(),
  "aboutUs": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Sobre nosotros"])};fn.source="Sobre nosotros";return fn;})(),
  "contact": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Contactos"])};fn.source="Contactos";return fn;})(),
  "services": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Servicios"])};fn.source="Servicios";return fn;})(),
  "mainPageH1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["ENC Tours culturales y patrimoniales"])};fn.source="ENC Tours culturales y patrimoniales";return fn;})(),
  "comp2p1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Inspiraciones"])};fn.source="Inspiraciones";return fn;})(),
  "comp2p2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["¡La emoción nunca termina con nosotros!"])};fn.source="¡La emoción nunca termina con nosotros!";return fn;})(),
  "comp2p3": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Inspirándonos en la abundancia de opciones de viaje en nuestra Asia, hemos viajado a cada rincón de nuestros queridos destinos para encontrar lo que definimos como recorridos ejemplares para los conocedores de viajes más exigentes."])};fn.source="Inspirándonos en la abundancia de opciones de viaje en nuestra Asia, hemos viajado a cada rincón de nuestros queridos destinos para encontrar lo que definimos como recorridos ejemplares para los conocedores de viajes más exigentes.";return fn;})(),
  "specialP1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["VIAJE DEL BOOM PETROLERO"])};fn.source="VIAJE DEL BOOM PETROLERO";return fn;})(),
  "specialP2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["VIAJE DE OBSERVACIÓN DE FLORES"])};fn.source="VIAJE DE OBSERVACIÓN DE FLORES";return fn;})(),
  "specialP3": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["VIAJE RELIGIOSO"])};fn.source="VIAJE RELIGIOSO";return fn;})(),
  "specialP4": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["VIAJE DE GOURMET"])};fn.source="VIAJE DE GOURMET";return fn;})(),
  "specialP5": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["TOUR DE OBSERVACIÓN DE AVES"])};fn.source="TOUR DE OBSERVACIÓN DE AVES";return fn;})(),
  "specialP6": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["TOUR DE GOLF"])};fn.source="TOUR DE GOLF";return fn;})(),
  "specialP7": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["VIAJE DE GRANADA"])};fn.source="VIAJE DE GRANADA";return fn;})(),
  "specialP8": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["VIAJE DE AGRICULTURA"])};fn.source="VIAJE DE AGRICULTURA";return fn;})(),
  "specialP9": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["VIAJE DE ALFOMBRAS"])};fn.source="VIAJE DE ALFOMBRAS";return fn;})(),
  "specialH1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["VIAJES DE INTERÉS ESPECIAL"])};fn.source="VIAJES DE INTERÉS ESPECIAL";return fn;})(),
  "specailH2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["LAUDED FOR ITS EXTENSIVE KNOWLEDGE, ITS EAST-MEETS-WEST MODEL AND VENTURING RESPONSIBLY INTO EVERY CORNER OF ITS DESTINATIONS, IT IS OUR MISSION TO SHOW GUESTS THE BEATING HEART OF OUR ASIA"])};fn.source="LAUDED FOR ITS EXTENSIVE KNOWLEDGE, ITS EAST-MEETS-WEST MODEL AND VENTURING RESPONSIBLY INTO EVERY CORNER OF ITS DESTINATIONS, IT IS OUR MISSION TO SHOW GUESTS THE BEATING HEART OF OUR ASIA";return fn;})()
},"it":{
  "home": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Startpagina"])};fn.source="Startpagina";return fn;})(),
  "aboutUs": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Sobre nosotros"])};fn.source="Sobre nosotros";return fn;})(),
  "contact": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Contactos"])};fn.source="Contactos";return fn;})(),
  "services": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Servicios"])};fn.source="Servicios";return fn;})(),
  "mainPageH1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["ENC Tours culturali e patrimoniali"])};fn.source="ENC Tours culturali e patrimoniali";return fn;})(),
  "comp2p1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Ispirazioni"])};fn.source="Ispirazioni";return fn;})(),
  "comp2p2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Da noi l'emozione non finisce mai!"])};fn.source="Da noi l'emozione non finisce mai!";return fn;})(),
  "comp2p3": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Ispirati dall'abbondanza di opzioni di viaggio nella nostra Asia, abbiamo viaggiato in ogni angolo delle nostre amate destinazioni per trovare quelli che definiamo tour esemplari per intenditori di viaggi esigenti"])};fn.source="Ispirati dall'abbondanza di opzioni di viaggio nella nostra Asia, abbiamo viaggiato in ogni angolo delle nostre amate destinazioni per trovare quelli che definiamo tour esemplari per intenditori di viaggi esigenti";return fn;})(),
  "specialP1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["TOUR DEL BOOM PETROLIFERO"])};fn.source="TOUR DEL BOOM PETROLIFERO";return fn;})(),
  "specialP2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["TOUR D’AMMIRAZIONE DEI FLOR"])};fn.source="TOUR D’AMMIRAZIONE DEI FLOR";return fn;})(),
  "specialP3": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["TOUR RELIGIOS"])};fn.source="TOUR RELIGIOS";return fn;})(),
  "specialP4": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["TOUR GOURMET"])};fn.source="TOUR GOURMET";return fn;})(),
  "specialP5": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["TOUR DI OSSERVAZIONE DEGLI UCCELLI"])};fn.source="TOUR DI OSSERVAZIONE DEGLI UCCELLI";return fn;})(),
  "specialP6": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["GOLF TOUR"])};fn.source="GOLF TOUR";return fn;})(),
  "specialP7": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["TOUR DEL MELOGRANO"])};fn.source="TOUR DEL MELOGRANO";return fn;})(),
  "specialP8": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["AGRICOLES TOUR"])};fn.source="AGRICOLES TOUR";return fn;})(),
  "specialP9": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["TOUR DI TAPPETTI"])};fn.source="TOUR DI TAPPETTI";return fn;})(),
  "specialH1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["TOUR DI INTERESSE SPECIALE"])};fn.source="TOUR DI INTERESSE SPECIALE";return fn;})(),
  "specailH2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["LAUDED FOR ITS EXTENSIVE KNOWLEDGE, ITS EAST-MEETS-WEST MODEL AND VENTURING RESPONSIBLY INTO EVERY CORNER OF ITS DESTINATIONS, IT IS OUR MISSION TO SHOW GUESTS THE BEATING HEART OF OUR ASIA"])};fn.source="LAUDED FOR ITS EXTENSIVE KNOWLEDGE, ITS EAST-MEETS-WEST MODEL AND VENTURING RESPONSIBLY INTO EVERY CORNER OF ITS DESTINATIONS, IT IS OUR MISSION TO SHOW GUESTS THE BEATING HEART OF OUR ASIA";return fn;})()
},"jp":{
  "home": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["家"])};fn.source="家";return fn;})(),
  "aboutUs": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["私たちについて"])};fn.source="私たちについて";return fn;})(),
  "contact": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["連絡先"])};fn.source="連絡先";return fn;})(),
  "services": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["サービス"])};fn.source="サービス";return fn;})(),
  "mainPageH1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["ENC ツアーの文化と伝統"])};fn.source="ENC ツアーの文化と伝統";return fn;})(),
  "comp2p1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["インスピレーション"])};fn.source="インスピレーション";return fn;})(),
  "comp2p2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["私たちの興奮は決して終わりません！"])};fn.source="私たちの興奮は決して終わりません！";return fn;})(),
  "comp2p3": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["アジアの豊富な旅行オプションに触発され、私たちは目の肥えた旅行愛好家のための模範的なツアーと定義するものを見つけるために、愛する目的地の隅々まで旅してきました。"])};fn.source="アジアの豊富な旅行オプションに触発され、私たちは目の肥えた旅行愛好家のための模範的なツアーと定義するものを見つけるために、愛する目的地の隅々まで旅してきました。";return fn;})(),
  "specialP1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["オイルブームと建築ツアー"])};fn.source="オイルブームと建築ツアー";return fn;})(),
  "specialP2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["花見ツアー"])};fn.source="花見ツアー";return fn;})(),
  "specialP3": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["宗教ツアー"])};fn.source="宗教ツアー";return fn;})(),
  "specialP4": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["グルメツアー"])};fn.source="グルメツアー";return fn;})(),
  "specialP5": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["バードウォッチングツアー"])};fn.source="バードウォッチングツアー";return fn;})(),
  "specialP6": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["ゴルフツアー"])};fn.source="ゴルフツアー";return fn;})(),
  "specialP7": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["ザクロツアー"])};fn.source="ザクロツアー";return fn;})(),
  "specialP8": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["農業ツアー"])};fn.source="農業ツアー";return fn;})(),
  "specialP9": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["カーペットと地元遺産ツアー"])};fn.source="カーペットと地元遺産ツアー";return fn;})(),
  "specialH1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["特別ツアー"])};fn.source="特別ツアー";return fn;})(),
  "specailH2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["LAUDED FOR ITS EXTENSIVE KNOWLEDGE, ITS EAST-MEETS-WEST MODEL AND VENTURING RESPONSIBLY INTO EVERY CORNER OF ITS DESTINATIONS, IT IS OUR MISSION TO SHOW GUESTS THE BEATING HEART OF OUR ASIA"])};fn.source="LAUDED FOR ITS EXTENSIVE KNOWLEDGE, ITS EAST-MEETS-WEST MODEL AND VENTURING RESPONSIBLY INTO EVERY CORNER OF ITS DESTINATIONS, IT IS OUR MISSION TO SHOW GUESTS THE BEATING HEART OF OUR ASIA";return fn;})()
},"fr":{
  "home": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Startpagina"])};fn.source="Startpagina";return fn;})(),
  "aboutUs": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Sobre nosotros"])};fn.source="Sobre nosotros";return fn;})(),
  "contact": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Contactos"])};fn.source="Contactos";return fn;})(),
  "services": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Servicios"])};fn.source="Servicios";return fn;})(),
  "mainPageH1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["ENC Tours culturais e patrimoniais"])};fn.source="ENC Tours culturais e patrimoniais";return fn;})(),
  "comp2p1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Inspirations"])};fn.source="Inspirations";return fn;})(),
  "comp2p2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["L'excitation ne s'arrête jamais chez nous !"])};fn.source="L'excitation ne s'arrête jamais chez nous !";return fn;})(),
  "comp2p3": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Inspirés par l'abondance d'options de voyage dans notre Asie, nous avons voyagé dans tous les coins et recoins de nos destinations préférées pour trouver ce que nous définissons comme des circuits exemplaires pour les connaisseurs de voyages exigeants."])};fn.source="Inspirés par l'abondance d'options de voyage dans notre Asie, nous avons voyagé dans tous les coins et recoins de nos destinations préférées pour trouver ce que nous définissons comme des circuits exemplaires pour les connaisseurs de voyages exigeants.";return fn;})(),
  "specialP1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["CIRCUIT DE BOOM PÉTROLIER"])};fn.source="CIRCUIT DE BOOM PÉTROLIER";return fn;})(),
  "specialP2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["CIRCUIT D’OBSERVATION DES FLEURS"])};fn.source="CIRCUIT D’OBSERVATION DES FLEURS";return fn;})(),
  "specialP3": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["CIRCUITS RELIGIEUX"])};fn.source="CIRCUITS RELIGIEUX";return fn;})(),
  "specialP4": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["VISITES GASTRONOMIQUES"])};fn.source="VISITES GASTRONOMIQUES";return fn;})(),
  "specialP5": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["VISITE D'OBSERVATION DES OISEAUX"])};fn.source="VISITE D'OBSERVATION DES OISEAUX";return fn;})(),
  "specialP6": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["TOUR DE GOLF"])};fn.source="TOUR DE GOLF";return fn;})(),
  "specialP7": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["GRENADE TOUR"])};fn.source="GRENADE TOUR";return fn;})(),
  "specialP8": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["L'AGRICULTURE TOURNÉE"])};fn.source="L'AGRICULTURE TOURNÉE";return fn;})(),
  "specialP9": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["VISITE GUIDÉE DES TAPIS"])};fn.source="VISITE GUIDÉE DES TAPIS";return fn;})(),
  "specialH1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["DES EXCURSIONS THÉMATIQUES SPÉCIALES"])};fn.source="DES EXCURSIONS THÉMATIQUES SPÉCIALES";return fn;})(),
  "specailH2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["LAUDED FOR ITS EXTENSIVE KNOWLEDGE, ITS EAST-MEETS-WEST MODEL AND VENTURING RESPONSIBLY INTO EVERY CORNER OF ITS DESTINATIONS, IT IS OUR MISSION TO SHOW GUESTS THE BEATING HEART OF OUR ASIA"])};fn.source="LAUDED FOR ITS EXTENSIVE KNOWLEDGE, ITS EAST-MEETS-WEST MODEL AND VENTURING RESPONSIBLY INTO EVERY CORNER OF ITS DESTINATIONS, IT IS OUR MISSION TO SHOW GUESTS THE BEATING HEART OF OUR ASIA";return fn;})()
},"pt":{
  "home": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Startpagina"])};fn.source="Startpagina";return fn;})(),
  "aboutUs": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Sobre nosotros"])};fn.source="Sobre nosotros";return fn;})(),
  "contact": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Contactos"])};fn.source="Contactos";return fn;})(),
  "services": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Servicios"])};fn.source="Servicios";return fn;})(),
  "mainPageH1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["ENC Tours culturais e patrimoniais"])};fn.source="ENC Tours culturais e patrimoniais";return fn;})(),
  "comp2p1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Inspirações"])};fn.source="Inspirações";return fn;})(),
  "comp2p2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["A emoção nunca acaba conosco!"])};fn.source="A emoção nunca acaba conosco!";return fn;})(),
  "comp2p3": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Inspirados pela abundância de opções de viagem na nossa Ásia, viajamos por todos os cantos dos nossos amados destinos para encontrar o que definimos como passeios exemplares para os conhecedores de viagens mais exigentes."])};fn.source="Inspirados pela abundância de opções de viagem na nossa Ásia, viajamos por todos os cantos dos nossos amados destinos para encontrar o que definimos como passeios exemplares para os conhecedores de viagens mais exigentes.";return fn;})(),
  "specialP1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["TOUR DE BOOM DO PETRÓLEO"])};fn.source="TOUR DE BOOM DO PETRÓLEO";return fn;})(),
  "specialP2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["VIAGENS DE OBSERVAÇÃO DE FLORES"])};fn.source="VIAGENS DE OBSERVAÇÃO DE FLORES";return fn;})(),
  "specialP3": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["VIAGENS RELIGIOSAS"])};fn.source="VIAGENS RELIGIOSAS";return fn;})(),
  "specialP4": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["TOUR GOURMET"])};fn.source="TOUR GOURMET";return fn;})(),
  "specialP5": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["OBSERVAÇÃO DE PÁSSAR"])};fn.source="OBSERVAÇÃO DE PÁSSAR";return fn;})(),
  "specialP6": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["TOUR DE GOLFE"])};fn.source="TOUR DE GOLFE";return fn;})(),
  "specialP7": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["VIAGEM DO ROMÃZEIRA"])};fn.source="VIAGEM DO ROMÃZEIRA";return fn;})(),
  "specialP8": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["TOUR AGRÍCOLA"])};fn.source="TOUR AGRÍCOLA";return fn;})(),
  "specialP9": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["TOUR DE CARPETE"])};fn.source="TOUR DE CARPETE";return fn;})(),
  "specialH1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["VIAGENS DO INTERESSE ESPECIAL"])};fn.source="VIAGENS DO INTERESSE ESPECIAL";return fn;})(),
  "specailH2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["LAUDED FOR ITS EXTENSIVE KNOWLEDGE, ITS EAST-MEETS-WEST MODEL AND VENTURING RESPONSIBLY INTO EVERY CORNER OF ITS DESTINATIONS, IT IS OUR MISSION TO SHOW GUESTS THE BEATING HEART OF OUR ASIA"])};fn.source="LAUDED FOR ITS EXTENSIVE KNOWLEDGE, ITS EAST-MEETS-WEST MODEL AND VENTURING RESPONSIBLY INTO EVERY CORNER OF ITS DESTINATIONS, IT IS OUR MISSION TO SHOW GUESTS THE BEATING HEART OF OUR ASIA";return fn;})()
},"kr":{
  "home": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["집"])};fn.source="집";return fn;})(),
  "aboutUs": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["회사 소개"])};fn.source="회사 소개";return fn;})(),
  "contact": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["콘택트 렌즈"])};fn.source="콘택트 렌즈";return fn;})(),
  "services": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["Servicios"])};fn.source="Servicios";return fn;})(),
  "mainPageH1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["ENC 투어 문화와 유산"])};fn.source="ENC 투어 문화와 유산";return fn;})(),
  "comp2p1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["영감"])};fn.source="영감";return fn;})(),
  "comp2p2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["흥분은 결코 끝나지 않습니다!"])};fn.source="흥분은 결코 끝나지 않습니다!";return fn;})(),
  "comp2p3": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["아시아의 다양한 여행 옵션에서 영감을 받아, 우리는 안목 있는 여행 감정가들을 위한 모범적인 여행으로 정의하는 것을 찾기 위해 우리가 사랑하는 목적지의 구석구석을 여행했습니다."])};fn.source="아시아의 다양한 여행 옵션에서 영감을 받아, 우리는 안목 있는 여행 감정가들을 위한 모범적인 여행으로 정의하는 것을 찾기 위해 우리가 사랑하는 목적지의 구석구석을 여행했습니다.";return fn;})(),
  "specialP1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["오일 붐과 건축 투어"])};fn.source="오일 붐과 건축 투어";return fn;})(),
  "specialP2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["꽃 감상 투어"])};fn.source="꽃 감상 투어";return fn;})(),
  "specialP3": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["종교 투어"])};fn.source="종교 투어";return fn;})(),
  "specialP4": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["미식가 투어"])};fn.source="미식가 투어";return fn;})(),
  "specialP5": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["조류 관찰 투어"])};fn.source="조류 관찰 투어";return fn;})(),
  "specialP6": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["골프 투어"])};fn.source="골프 투어";return fn;})(),
  "specialP7": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["석류 투어"])};fn.source="석류 투어";return fn;})(),
  "specialP8": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["농업관광"])};fn.source="농업관광";return fn;})(),
  "specialP9": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["카펫 및 지역 문화유산 투어"])};fn.source="카펫 및 지역 문화유산 투어";return fn;})(),
  "specialH1": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["특별 테마 여행"])};fn.source="특별 테마 여행";return fn;})(),
  "specailH2": (()=>{const fn=(ctx) => {const { normalize: _normalize } = ctx;return _normalize(["LAUDED FOR ITS EXTENSIVE KNOWLEDGE, ITS EAST-MEETS-WEST MODEL AND VENTURING RESPONSIBLY INTO EVERY CORNER OF ITS DESTINATIONS, IT IS OUR MISSION TO SHOW GUESTS THE BEATING HEART OF OUR ASIA"])};fn.source="LAUDED FOR ITS EXTENSIVE KNOWLEDGE, ITS EAST-MEETS-WEST MODEL AND VENTURING RESPONSIBLY INTO EVERY CORNER OF ITS DESTINATIONS, IT IS OUR MISSION TO SHOW GUESTS THE BEATING HEART OF OUR ASIA";return fn;})()
},}),})
  nuxtI18nOptions.vueI18n = await vueI18nOptionsLoader(context)
  nuxtI18nOptions.locales = ["en","de","es","it","jp","fr","pt","kr"]
  nuxtI18nOptions.defaultLocale = "en"
  nuxtI18nOptions.defaultDirection = "ltr"
  nuxtI18nOptions.routesNameSeparator = "___"
  nuxtI18nOptions.trailingSlash = false
  nuxtI18nOptions.defaultLocaleRouteNameSuffix = "default"
  nuxtI18nOptions.strategy = "prefix_except_default"
  nuxtI18nOptions.lazy = false
  nuxtI18nOptions.langDir = null
  nuxtI18nOptions.rootRedirect = null
  nuxtI18nOptions.detectBrowserLanguage = Object({"alwaysRedirect":false,"cookieCrossOrigin":false,"cookieDomain":null,"cookieKey":"i18n_redirected","cookieSecure":false,"fallbackLocale":"","redirectOn":"root","useCookie":true})
  nuxtI18nOptions.differentDomains = false
  nuxtI18nOptions.baseUrl = ""
  nuxtI18nOptions.dynamicRouteParams = false
  nuxtI18nOptions.customRoutes = "page"
  nuxtI18nOptions.pages = Object({})
  nuxtI18nOptions.skipSettingLocaleOnNavigate = false
  nuxtI18nOptions.onBeforeLanguageSwitch = (() => "")
  nuxtI18nOptions.onLanguageSwitched = (() => null)
  nuxtI18nOptions.types = undefined
  nuxtI18nOptions.debug = false
  return nuxtI18nOptions
}

export const nuxtI18nOptionsDefault = Object({vueI18n: undefined,locales: [],defaultLocale: "",defaultDirection: "ltr",routesNameSeparator: "___",trailingSlash: false,defaultLocaleRouteNameSuffix: "default",strategy: "prefix_except_default",lazy: false,langDir: null,rootRedirect: null,detectBrowserLanguage: Object({"alwaysRedirect":false,"cookieCrossOrigin":false,"cookieDomain":null,"cookieKey":"i18n_redirected","cookieSecure":false,"fallbackLocale":"","redirectOn":"root","useCookie":true}),differentDomains: false,baseUrl: "",dynamicRouteParams: false,customRoutes: "page",pages: Object({}),skipSettingLocaleOnNavigate: false,onBeforeLanguageSwitch: (() => ""),onLanguageSwitched: (() => null),types: undefined,debug: false})

export const nuxtI18nInternalOptions = Object({__normalizedLocales: [Object({"code":"en","iso":"en"}),Object({"code":"de","iso":"de"}),Object({"code":"es","iso":"es"}),Object({"code":"it","iso":"it"}),Object({"code":"jp","iso":"jp"}),Object({"code":"fr","iso":"fr"}),Object({"code":"pt","iso":"pt"}),Object({"code":"kr","iso":"kr"})]})
export const NUXT_I18N_MODULE_ID = "@nuxtjs/i18n"
export const isSSG = false
export const isSSR = true
